# Generated by Django 4.0.4 on 2022-11-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0012_cashbook_like_count_alter_cashbook_user'),
        ('account', '0012_user_password1_user_password2_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='cashbookapp.cashbook'),
        ),
    ]
