# Generated by Django 4.0.4 on 2022-09-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0002_cashbook_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
