# Generated by Django 4.0.4 on 2022-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0004_alter_cashbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='feeling',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
