# Generated by Django 4.0.4 on 2022-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0006_alter_cashbook_image_alter_cashbook_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='feeling',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
