# Generated by Django 4.0.4 on 2022-11-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0013_rename_name_hashtag_hashtag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hashtag_name',
            new_name='name',
        ),
    ]
